### ISSUE TITLE
Rounding functions

### ISSUE THREAD

**Issue by chmodseven** [danm-de/Fractions#23] opened 2024-03-23 13:14 UTC
Would it be possible to add methods for Floor / Ceil / Round to round the Fraction to the nearest integer?  This would be helpful for cases where for example you want to convert out afterwards to BigInteger or other integer types, but doing so at the moment will lose the information from the fractional value to allow for the appropriate rounding to be performed.

I know that for small enough values I could do the rounding via a decimal or double workaround step first, but when it comes to BigInteger there isn't a similar workaround.  The use case I have is for an incremental game where I want to multiply very large BigInteger numbers by a fractional scalar, for example 1.3x.  I'm doing this by performing the calculation as Fraction and then using .ToBigInteger afterwards, but this is always returning a floored integer and ideally I'd like to have the options of round or ceil as well, without having to write some clunky > or < comparison code.

**Comment by danm-de** [comment] 2024-03-24 18:33
Hi @chmodseven ,

> Would it be possible to add methods for Floor / Ceil / Round to round the Fraction to the nearest integer?

Feel free to open a pull request with your proposed implementation. I will close this issue as it is not a bug report but a feature request.

Greetings, 
Daniel

**Closed by danm-de** 2024-03-24 18:33 UTC
